name = "getty.service"

[unit]
description = "Serial console auto-login on ttyAMA0"

[service]
exec_start = ["/bin/getty", "-a", "root", "115200", "ttyAMA0"]
type = "simple"
restart = "always"
restart_sec = 1
