name = "getty.service"

[unit]
description = "Serial console shell on ttyAMA0"

[service]
exec_start = ["/sbin/getty", "-n", "-l", "/bin/sh", "115200", "ttyAMA0"]
type = "simple"
restart = "always"
restart_sec = 1
