name = "getty.service"

[unit]
description = "Native serial console shell on ttyAMA0"

[service]
exec_start = ["/bin/sh"]
type = "simple"
tty = "ttyAMA0"
tty_baud = 115200
restart = "always"
restart_sec = 1
